name: Build css
on:
  push:
    branches:
      - "Test"
      
# Conditional environmental if's      
env:
  UPDATE_NPM: false # false = deploy css , true = update npm

jobs:
  build_css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # cache: 'npm'

      - name: Install dependencies
        run: npm install  #npm update  --save
        
      - name: Npm build
        if: env.UPDATE_NPM != 'true'
        run: npm run build
        
      - name: Commit changes
        if: env.UPDATE_NPM != 'true'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Add files"
          add: '["*.json", "*.scss", "*.css", "*.js"]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
      - name: pull request on npm update
        if: env.UPDATE_NPM == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates
  
            Auto-generated by [create-pull-request][1]
  
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
